In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import requests
from sklearn.preprocessing import StandardScaler

In [3]:
api_key="ed6e8fd930c5350bde153e601cef979c"
city_name="jaipur"
url=f"https://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={api_key}"


In [34]:
res=requests.get(url)
data=res.json()
print(data)
report={
    'city':data["name"],
    'temp':data["main"]["temp"],
    'mintemp':data["main"]["temp_min"],
    'maxtemp':data["main"]["temp_max"],
    'pressure':data["main"]["pressure"],
    'humidity':data['main']['humidity']
    }
print(report)
current_meantemp =data["main"]["temp"]
current_meanpressure =data["main"]["pressure"]
current_mintemp=data["main"]["temp_min"]
current_maxtemp=data["main"]["temp_max"]
current_humidity=data['main']['humidity']



{'coord': {'lon': 75.8167, 'lat': 26.9167}, 'weather': [{'id': 721, 'main': 'Haze', 'description': 'haze', 'icon': '50n'}], 'base': 'stations', 'main': {'temp': 300.77, 'feels_like': 300.43, 'temp_min': 300.77, 'temp_max': 300.77, 'pressure': 1011, 'humidity': 39, 'sea_level': 1011, 'grnd_level': 964}, 'visibility': 3000, 'wind': {'speed': 1.54, 'deg': 0}, 'clouds': {'all': 40}, 'dt': 1729524479, 'sys': {'type': 1, 'id': 9170, 'country': 'IN', 'sunrise': 1729472373, 'sunset': 1729513369}, 'timezone': 19800, 'id': 1269515, 'name': 'Jaipur', 'cod': 200}
{'city': 'Jaipur', 'temp': 300.77, 'mintemp': 300.77, 'maxtemp': 300.77, 'pressure': 1011, 'humidity': 39}


In [35]:

df=pd.read_csv("JaipurFinalCleanData.csv")
print(df)

    

           date  meantempm  maxtempm  mintempm  meantempm_1  meantempm_2  \
0    2016-05-04         34        41        27         35.0         36.0   
1    2016-05-05         31        38        24         34.0         35.0   
2    2016-05-06         28        34        21         31.0         34.0   
3    2016-05-07         30        38        23         28.0         31.0   
4    2016-05-08         34        41        26         30.0         28.0   
..          ...        ...       ...       ...          ...          ...   
671  2018-03-07         24        32        15         22.0         23.0   
672  2018-03-08         24        32        15         24.0         22.0   
673  2018-03-09         26        33        19         24.0         24.0   
674  2018-03-10         26        34        19         26.0         24.0   
675  2018-03-11         26        34        18         26.0         26.0   

     meantempm_3  meandewptm_1  meandewptm_2  meandewptm_3  ...  mindewptm_3  \
0      

In [40]:
# Selected features
features = ['meantempm_1', 
            'meanpressurem_1', 
            'maxhumidity_1', 
            'minhumidity_1', 
            'maxtempm_1', 
            'mintempm_1']

# Target variable
target = 'meantempm'

# Split the data into features (X) and target (y)
X = df[features]
y = df[target]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Check the scaled training and testing data
print(X_train_scaled)
print(X_test_scaled)


[[-0.97201105  1.28627367  0.4620532  -0.63296307 -0.58899645 -1.26120391]
 [ 1.91550344 -1.72662271 -1.66392762 -0.83939524  2.05460321  1.81516786]
 [-1.292846    0.96009556 -0.39738586 -0.83939524 -1.24989637 -1.26120391]
 ...
 [-1.77409841  1.64491501  1.50242679  0.60562992 -1.91079629 -1.5541917 ]
 [ 0.63216367 -0.97842269  0.77868864  1.22492642  0.07190346  0.9362045 ]
 [ 0.31132872 -0.92122558  1.50242679  2.10226313 -0.09332152  0.64321671]]
[[-1.292846    1.11777408 -0.7140213  -0.7877872  -1.24989637 -1.26120391]
 [-0.16992369  0.54116538 -0.80448857 -0.58135503 -0.09332152 -0.23574665]
 [ 1.5946685  -0.24413547 -1.93532943 -0.94261132  1.88937824  1.37568618]
 [ 0.63216367 -0.42809374  1.00485681  0.4508058   0.5675784   0.64321671]
 [-1.292846    0.93536168 -0.39738586 -0.22009874 -1.41512135 -1.11471002]
 [ 1.27383356 -1.18247724 -0.03551678  0.39919776  1.06325334  1.37568618]
 [-1.292846    0.70966498 -1.03065674 -0.63296307 -1.24989637 -1.4076978 ]
 [-1.93451588  1.35

In [41]:
# Initialize the Random Forest model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
rf_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = rf_model.predict(X_test_scaled)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')


Mean Squared Error: 2.7796080882352947


In [45]:
# Example input for future prediction (replace these with actual values)
latest_weather_data = [[current_meantemp, current_meanpressure, current_humidity, current_humidity, current_maxtemp, current_mintemp]]

# Convert the latest input data to a pandas DataFrame with the same feature names used during training
latest_weather_data_df = pd.DataFrame(latest_weather_data, columns=['meantempm_1', 'meanpressurem_1', 'maxhumidity_1', 'minhumidity_1', 'maxtempm_1', 'mintempm_1'])

# Scale the input data
latest_weather_data_scaled = scaler.transform(latest_weather_data_df)

# Predict future temperature
future_temp_prediction = rf_model.predict(latest_weather_data_scaled)

# Output the predicted temperature
print(f'Predicted Temperature: {future_temp_prediction[0]}')


Predicted Temperature: 34.98
